name: CI bpm-ai-core
on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'bpm-ai-core/**'

jobs:
  pytest:
    defaults:
      run:
        working-directory: ./bpm-ai-core/tests
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        run: sudo apt-get install -y tesseract-ocr poppler-utils
      -
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      -
        name: Set up poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      -
        name: Install dependencies
        run: poetry install
      -
        name: Run pytest
        run: poetry run pytest
